### ISSUE TITLE
Automatically starting language server

### ISSUE THREAD

**Issue by SchneiderMaster** [grafana/vscode-jsonnet#45]
Hi,

I am wondering if it was possible to somehow start the language server automatically. I am trying to setup a devcontainer with this extension enabled and downloading jsonnet in a post-script.

I am currently doing the following, however, executing it only results in no response from the executable and no running server:

```bash
#!/bin/bash

# install some libraries
echo "Installing libraries..."
go install github.com/google/go-jsonnet/cmd/jsonnet@latest 
go install -a github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb@latest 
jb install github.com/grafana/grafonnet/gen/grafonnet-latest@main 

# activate and download jsonnet language server 
mkdir -p /home/vscode/.vscode-server/data/User/globalStorage/grafana.vscode-jsonnet/bin/ 
curl https://github.com/grafana/jsonnet-language-server/releases/download/v0.14.1/jsonnet-language-server_0.14.1_linux_amd64 -o /home/vscode/.vscode-server/data/User/globalStorage/grafana.vscode-jsonnet/bin/jsonnet-language-server 

chmod +x /home/vscode/.vscode-server/data/User/globalStorage/grafana.vscode-jsonnet/bin/jsonnet-language-server
```

Is there a way to have the language server automatically run whenever I open the devcontainer without having to manually press the button that pops up after a few seconds?

Edit:
The Jsonnet Extension outputs that it can't find the version, logs that it starts but doesn't.

```
Not using custom binary path. Using default path for languageServer
Binary path is /home/vscode/.vscode-server/data/User/globalStorage/grafana.vscode-jsonnet/bin/jsonnet-language-server (exists: true)
Auto-update is enabled. Fetching latest release from https://api.github.com/repos/grafana/jsonnet-language-server/releases/latest
Latest release is 0.14.1
Failed to get current version from /home/vscode/.vscode-server/data/User/globalStorage/grafana.vscode-jsonnet/bin/jsonnet-language-server
Error: Invalid version string
Not updating the language server.
Jsonnet Language Server will start: '/home/vscode/.vscode-server/data/User/globalStorage/grafana.vscode-jsonnet/bin/jsonnet-language-server --log-level info --tanka'
```

Further logs from the language server:

```
[Error - 11:21:48 AM] Client Jsonnet Language Server: connection to server is erroring. Shutting down server.
[Error - 11:21:48 AM] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: starting
	at LanguageClient.shutdown (/home/vscode/.vscode-server/extensions/grafana.vscode-jsonnet-0.6.1/node_modules/vscode-languageclient/lib/common/client.js:897:19)
	at LanguageClient.stop (/home/vscode/.vscode-server/extensions/grafana.vscode-jsonnet-0.6.1/node_modules/vscode-languageclient/lib/common/client.js:868:21)
	at LanguageClient.stop (/home/vscode/.vscode-server/extensions/grafana.vscode-jsonnet-0.6.1/node_modules/vscode-languageclient/lib/node/main.js:150:22)
	at LanguageClient.handleConnectionError (/home/vscode/.vscode-server/extensions/grafana.vscode-jsonnet-0.6.1/node_modules/vscode-languageclient/lib/common/client.js:1104:18)
	at errorHandler (/home/vscode/.vscode-server/extensions/grafana.vscode-jsonnet-0.6.1/node_modules/vscode-languageclient/lib/common/client.js:1047:18)
	at /home/vscode/.vscode-server/extensions/grafana.vscode-jsonnet-0.6.1/node_modules/vscode-languageclient/lib/common/client.js:1417:36
	at CallbackList.invoke (/home/vscode/.vscode-server/extensions/grafana.vscode-jsonnet-0.6.1/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/home/vscode/.vscode-server/extensions/grafana.vscode-jsonnet-0.6.1/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at writeErrorHandler (/home/vscode/.vscode-server/extensions/grafana.vscode-jsonnet-0.6.1/node_modules/vscode-jsonrpc/lib/common/connection.js:299:22)
	at CallbackList.invoke (/home/vscode/.vscode-server/extensions/grafana.vscode-jsonnet-0.6.1/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/home/vscode/.vscode-server/extensions/grafana.vscode-jsonnet-0.6.1/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at StreamMessageWriter.fireError (/home/vscode/.vscode-server/extensions/grafana.vscode-jsonnet-0.6.1/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:36:27)
	at Socket.<anonymous> (/home/vscode/.vscode-server/extensions/grafana.vscode-jsonnet-0.6.1/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:73:47)
	at Socket.emit (node:events:519:28)
	at emitErrorNT (node:internal/streams/destroy:169:8)
	at emitErrorCloseNT (node:internal/streams/destroy:128:3)
	at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[Info  - 11:21:48 AM] Connection to server got closed. Server will restart.
[Error - 11:21:48 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 11:21:48 AM] Jsonnet Language Server client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 11:21:48 AM] Connection to server got closed. Server will restart.
[Error - 11:21:48 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 11:21:48 AM] Jsonnet Language Server client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 11:21:48 AM] Client Jsonnet Language Server: connection to server is erroring. Shutting down server.
[Error - 11:21:48 AM] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: startFailed
	at LanguageClient.shutdown (/home/vscode/.vscode-server/extensions/grafana.vscode-jsonnet-0.6.1/node_modules/vscode-languageclient/lib/common/client.js:897:19)
	at LanguageClient.stop (/home/vscode/.vscode-server/extensions/grafana.vscode-jsonnet-0.6.1/node_modules/vscode-languageclient/lib/common/client.js:868:21)
	at LanguageClient.stop (/home/vscode/.vscode-server/extensions/grafana.vscode-jsonnet-0.6.1/node_modules/vscode-languageclient/lib/node/main.js:150:22)
	at LanguageClient.handleConnectionError (/home/vscode/.vscode-server/extensions/grafana.vscode-jsonnet-0.6.1/node_modules/vscode-languageclient/lib/common/client.js:1104:18)
	at errorHandler (/home/vscode/.vscode-server/extensions/grafana.vscode-jsonnet-0.6.1/node_modules/vscode-languageclient/lib/common/client.js:1047:18)
	at /home/vscode/.vscode-server/extensions/grafana.vscode-jsonnet-0.6.1/node_modules/vscode-languageclient/lib/common/client.js:1417:36
	at CallbackList.invoke (/home/vscode/.vscode-server/extensions/grafana.vscode-jsonnet-0.6.1/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/home/vscode/.vscode-server/extensions/grafana.vscode-jsonnet-0.6.1/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at writeErrorHandler (/home/vscode/.vscode-server/extensions/grafana.vscode-jsonnet-0.6.1/node_modules/vscode-jsonrpc/lib/common/connection.js:299:22)
	at CallbackList.invoke (/home/vscode/.vscode-server/extensions/grafana.vscode-jsonnet-0.6.1/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/home/vscode/.vscode-server/extensions/grafana.vscode-jsonnet-0.6.1/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at StreamMessageWriter.fireError (/home/vscode/.vscode-server/extensions/grafana.vscode-jsonnet-0.6.1/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:36:27)
	at Socket.<anonymous> (/home/vscode/.vscode-server/extensions/grafana.vscode-jsonnet-0.6.1/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:73:47)
	at Socket.emit (node:events:519:28)
	at emitErrorNT (node:internal/streams/destroy:169:8)
	at emitErrorCloseNT (node:internal/streams/destroy:128:3)
	at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[Info  - 11:21:48 AM] Connection to server got closed. Server will restart.
[Error - 11:21:48 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 11:21:48 AM] Jsonnet Language Server client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 11:21:48 AM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 11:21:48 AM] Connection to server got closed. Server will restart.
[Error - 11:21:48 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 11:21:48 AM] Jsonnet Language Server client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 11:21:48 AM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 11:21:49 AM] Client Jsonnet Language Server: connection to server is erroring. Shutting down server.
[Error - 11:21:49 AM] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: startFailed
	at LanguageClient.shutdown (/home/vscode/.vscode-server/extensions/grafana.vscode-jsonnet-0.6.1/node_modules/vscode-languageclient/lib/common/client.js:897:19)
	at LanguageClient.stop (/home/vscode/.vscode-server/extensions/grafana.vscode-jsonnet-0.6.1/node_modules/vscode-languageclient/lib/common/client.js:868:21)
	at LanguageClient.stop (/home/vscode/.vscode-server/extensions/grafana.vscode-jsonnet-0.6.1/node_modules/vscode-languageclient/lib/node/main.js:150:22)
	at LanguageClient.handleConnectionError (/home/vscode/.vscode-server/extensions/grafana.vscode-jsonnet-0.6.1/node_modules/vscode-languageclient/lib/common/client.js:1104:18)
	at errorHandler (/home/vscode/.vscode-server/extensions/grafana.vscode-jsonnet-0.6.1/node_modules/vscode-languageclient/lib/common/client.js:1047:18)
	at /home/vscode/.vscode-server/extensions/grafana.vscode-jsonnet-0.6.1/node_modules/vscode-languageclient/lib/common/client.js:1417:36
	at CallbackList.invoke (/home/vscode/.vscode-server/extensions/grafana.vscode-jsonnet-0.6.1/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/home/vscode/.vscode-server/extensions/grafana.vscode-jsonnet-0.6.1/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at writeErrorHandler (/home/vscode/.vscode-server/extensions/grafana.vscode-jsonnet-0.6.1/node_modules/vscode-jsonrpc/lib/common/connection.js:299:22)
	at CallbackList.invoke (/home/vscode/.vscode-server/extensions/grafana.vscode-jsonnet-0.6.1/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/home/vscode/.vscode-server/extensions/grafana.vscode-jsonnet-0.6.1/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at StreamMessageWriter.fireError (/home/vscode/.vscode-server/extensions/grafana.vscode-jsonnet-0.6.1/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:36:27)
	at Socket.<anonymous> (/home/vscode/.vscode-server/extensions/grafana.vscode-jsonnet-0.6.1/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:73:47)
	at Socket.emit (node:events:519:28)
	at emitErrorNT (node:internal/streams/destroy:169:8)
	at emitErrorCloseNT (node:internal/streams/destroy:128:3)
	at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[Error - 11:21:49 AM] The Jsonnet Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 11:21:49 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 11:21:49 AM] Jsonnet Language Server client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 11:21:49 AM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
```

**Comment by SchneiderMaster** [comment]
Ok it turns out to be that I just made a mistake by forgetting the -L option on curl, it now works as expected, but I would still be happy to see the language server and debugger being activated automatically with the extension in the future 🙌
