### ISSUE TITLE
v0.7.1 & v0.7.2 Request textDocument/documentSymbol failed

### ISSUE THREAD

**Issue by keith-hopkins-sada** [grafana/vscode-jsonnet#50]
This error, and many more like it, are seen in v0.7.1 & v0.7.2, but not v0.7.0.  

[Error - 3:33:19 PM] Request textDocument/documentSymbol failed.
Error: name must not be falsy
	at Hd.validate (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:108:33594)
	at new Hd (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:108:33883)
	at asDocumentSymbol (/Users/username/.vscode/extensions/grafana.vscode-jsonnet-0.7.2/node_modules/vscode-languageclient/lib/common/protocolConverter.js:604:22)
	at convertBatch (/Users/username/.vscode/extensions/grafana.vscode-jsonnet-0.7.2/node_modules/vscode-languageclient/lib/common/utils/async.js:193:25)
	at Object.map (/Users/username/.vscode/extensions/grafana.vscode-jsonnet-0.7.2/node_modules/vscode-languageclient/lib/common/utils/async.js:202:17)
	at Object.asDocumentSymbols (/Users/username/.vscode/extensions/grafana.vscode-jsonnet-0.7.2/node_modules/vscode-languageclient/lib/common/protocolConverter.js:601:22)
	at _provideDocumentSymbols (/Users/username/.vscode/extensions/grafana.vscode-jsonnet-0.7.2/node_modules/vscode-languageclient/lib/common/documentSymbol.js:83:76)
	at async OC.provideDocumentSymbols (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:137:125496)

Visual Studio Code
Version: 1.95.1 (Universal)
Date: 2024-10-31T05:14:54.222Z (6 days ago)
OS: Darwin arm64 24.1.0

The jsonnet file is ~550 lines long, and the 17 yaml files produced with it all pass `kubecfg validate`.

Any suggestions on how to narrow down the cause would be appreciated.

**Comment by julienduchesne** [comment]
This should be fixed with the latest language server version v0.15.0

**Comment by keith-hopkins-sada** [comment]
Hi @julienduchesne, sorry, could you clarify, which "language server" is v0.15.0?   When I pull main here, it's still v0.7.2.

**Comment by keith-hopkins-sada** [comment]
ok, found https://github.com/grafana/jsonnet-language-server/releases/tag/v0.15.0
